version: '3'
services:
  frontend:
    image: jeremye7/pis_frontend:latest
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3000/api/v1
    ports:
      - 3006:3006
    depends_on:
      - backend
  backend:
    image: jeremye7/pis_backend:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/PISDATABASE
      - SECRET_KEY= JJJA
    command: "npm run dev"
    depends_on:
      - db
    restart: on-failure
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PISDATABASE
      MYSQL_WAIT_TIMEOUT: 600  
      MYSQL_INTERACTIVE_TIMEOUT: 600  
      MYSQL_INITDB_SKIP_TZINFO: 1  
    volumes:
      - db_data:/var/lib/mysql
volumes:
    db_data: